import 'dart:collection';

const List<String> europeCountries = [
  "BE",
  "BG",
  "CZ",
  "DK",
  "DE",
  "EE",
  "IE",
  "EL",
  "ES",
  "FR",
  "HR",
  "IT",
  "CY",
  "LV",
  "LT",
  "LU",
  "HU",
  "MT",
  "NL",
  "AT",
  "PL",
  "PT",
  "RO",
  "SI",
  "SK",
  "FI",
  "SE",
  "IS",
  "NO",
  "CH",
  "UK",
  "ME",
  "MK",
  "AL",
  "RS",
  "TR",
];

final Map<String, List<String>> europeEq = HashMap()..addAll(
    {"BE" : ["Belgium"],
      "BG" : ["Bulgaria"],
      "CZ" : ["Czechia"],
      "DK" : ["Denmark"],
      "DE" : ["Germany"],
      "EE" : ["Estonia"],
      "IE" : ["Ireland"],
      "EL" : ["Greece"],
      "ES" : ["Spain"],
      "FR" : ["France"],
      "HR" : ["Croatia"],
      "IT" : ["Italy"],
      "CY" : ["Cyprus"],
      "LV" : ["Latvia"],
      "LT" : ["Lithuania"],
      "LU" : ["Luxembourg"],
      "HU" : ["Hungary"],
      "MT" : ["Malta"],
      "NL" : ["Netherlands"],
      "AT" : ["Austria"],
      "PL" : ["Poland"],
      "PT" : ["Portugal"],
      "RO" : ["Romania"],
      "SI" : ["Slovania"],
      "SK" : ["Slovakia"],
      "FI" : ["Finland"],
      "SE" : ["Sweden"],
      "IS" : ["Iceland"],
      "NO" : ["Norway"],
      "CH" : ["Swirzerland"],
      "UK" : ["United Kingdom"],
      "ME" : ["Montenegro"],
      "MK" : ["North Macedonia"],
      "AL" : ["Alabania"],
      "RS" : ["Serbia"],
      "TR" : ["Türkiye"]
    }
);